extends Node

const ShieldRegenPerStep = 2
const HoverKnightTileOffsetX = 2
const SlowPercent = 50

var cards = {
# units
	"archengineer": {
		"Cost":    5000,
		"Unit":    "archengineer",
		"Count":   1,
		"OffsetX": [0],
		"OffsetY": [0],
		"Rarity":  "Common",
	},
	"archers": {
		"Cost":    3000,
		"Unit":    "archer",
		"Count":   2,
		"OffsetX": [-40, 40],
		"OffsetY": [0, 0],
		"Rarity":  "Common",
	},
	"archsapper": {
		"Cost":    3000,
		"Unit":    "archsapper",
		"Count":   1,
		"OffsetX": [0],
		"OffsetY": [0],
		"Rarity":  "Common",
	},
	"astra": {
		"Cost":    4000,
		"Unit":    "astra",
		"Count":   1,
		"OffsetX": [0],
		"OffsetY": [0],
		"Rarity":  "Common",
	},
	"berserker": {
		"Cost":    4000,
		"Unit":    "berserker",
		"Count":   1,
		"OffsetX": [0],
		"OffsetY": [0],
		"Rarity":  "Common",
	},
	"blaster": {
		"Cost": 3000,
		"Unit": "blaster",
		"Count": 1,
		"OffsetX": [0],
		"OffsetY": [0],
		"Rarity":  "Common",
	},
	"champion": {
		"Cost":    4000,
		"Unit":    "champion",
		"Count":   1,
		"OffsetX": [0],
		"OffsetY": [0],
		"Rarity":  "Common",
	},
	"drillram": {
		"Cost": 4000,
		"Unit": "drillram",
		"Count": 1,
		"OffsetX": [0],
		"OffsetY": [0],
		"Rarity":  "Common",
	},
	"enforcer": {
		"Cost":    4000,
		"Unit":    "enforcer",
		"Count":   1,
		"OffsetX": [0],
		"OffsetY": [0],
		"Rarity":  "Common",
	},
	"felhound": {
		"Cost":    2000,
		"Unit":    "felhound",
		"Count":   5,
		"OffsetX": [-60, 0, 60, -30, 30],
		"OffsetY": [-30, -30, -30, 30, 30],
		"Rarity":  "Common",
	},
	"footmans": {
		"Cost":    5000,
		"Unit":    "footman",
		"Count":   4,
		"OffsetX": [-30, 30, -30, 30],
		"OffsetY": [-30, -30, 30, 30],
		"Rarity":  "Common",
	},
	"frost": {
		"Cost":    4000,
		"Unit":    "frost",
		"Count":   1,
		"OffsetX": [0],
		"OffsetY": [0],
	},
	"gargoylehorde": {
		"Cost":    5000,
		"Unit":    "gargoyle",
		"Count":   6,
		"OffsetX": [-40, 0, 40, -40, 0, 40],
		"OffsetY": [-20, -20, -20, 20, 20, 20],
		"Rarity":  "Common",
	},
	"gargoyleking": {
		"Cost":    3000,
		"Unit":    "gargoyleking",
		"Count":   1,
		"OffsetX": [0],
		"OffsetY": [0],
		"Rarity":  "Common",
	},
	"giant": {
		"Cost": 5000,
		"Unit": "giant",
		"Count": 1,
		"OffsetX": [0],
		"OffsetY": [0],
		"Rarity":  "Common",
	},
	"ironcoffin": {
		"Cost":    5000,
		"Unit":    "ironcoffin",
		"Count":   1,
		"OffsetX": [0],
		"OffsetY": [0],
		"Rarity":  "Common",
	},
	"jouster": {
		"Cost":    5000,
		"Unit":    "jouster",
		"Count":   1,
		"OffsetX": [0],
		"OffsetY": [0],
		"Rarity":  "Common",
	},
	"judge": {
		"Cost":   3000,
		"Unit":    "judge",
		"Count":   1,
		"OffsetX": [0],
		"OffsetY": [0],
		"Rarity":  "Common",
	},
	"lancer": {
		"Cost":    5000,
		"Unit":    "lancer",
		"Count":   1,
		"OffsetX": [0],
		"OffsetY": [0],
		"Rarity":  "Common",
	},
	"legion": {
		"Cost":    4000,
		"Unit":    "legion",
		"Count":   1,
		"OffsetX": [0],
		"OffsetY": [0],
		"Rarity":  "Common",
	},
	"nagmash": {
		"Cost":    4000,
		"Unit":   "nagmash",
		"Count":   4,
		"OffsetX": [-30, 30, -30, 30],
		"OffsetY": [-30, -30, 30, 30],
		"Rarity":  "Common",
	},
	"ogre": {
		"Cost":    7000,
		"Unit":    "ogre",
		"Count":   1,
		"OffsetX": [0],
		"OffsetY": [0],
		"Rarity":  "Common",
	},
	"panzerkunstler": {
		"Cost":    5000,
		"Unit":    "panzerkunstler",
		"Count":   1,
		"OffsetX": [0],
		"OffsetY": [0],
		"Rarity":  "Common",
	},
	"pixie": {
		"Cost":    1000,
		"Unit":    "pixie",
		"Count":   3,
		"OffsetX": [-30, 30, 0],
		"OffsetY": [30, 30, 0],
		"Rarity":  "Common",
	},
	"pixieking": {
		"Cost":    3000,
		"Unit":    "pixieking",
		"Count":   1,
		"OffsetX": [0],
		"OffsetY": [0],
		"Rarity":  "Common",
	},
	"psabu": {
		"Cost":    7000,
		"Unit":    "psabu",
		"Count":   1,
		"OffsetX": [0],
		"OffsetY": [0],
		"Rarity":  "Common",
	},
	"sentry": {
		"Cost":    2000,
		"Unit":    "sentry",
		"Count":   3,
		"OffsetX": [-30, 30, 0],
		"OffsetY": [30, 30, 0],
		"Rarity":  "Common",
	},
	"shadowvision": {
		"Cost":    4000,
		"Unit":    "shadowvision",
		"Count":   1,
		"OffsetX": [0],
		"OffsetY": [0],
		"Rarity":  "Common",
	},
	"starfire": {
		"Cost":    4000,
		"Unit":    "starfire",
		"Count":   1,
		"OffsetX": [0],
		"OffsetY": [0],
		"Rarity":  "Common",
	},
	"threestarfires": {
		"Cost":    9000,
		"Unit":    "starfire",
		"Count":   3,
		"OffsetX": [-60, 60, 0],
		"OffsetY": [60, 60, 0],
		"Rarity":  "Common",
	},
	"tombstone": {
		"Cost":    7000,
		"Unit":    "tombstone",
		"Count":   1,
		"OffsetX": [0],
		"OffsetY": [0],
		"Rarity":  "Common",
	},
	"trainee": {
		"Cost":    2000,
		"Unit":    "trainee",
		"Count":   3,
		"OffsetX": [-30, 30, 0],
		"OffsetY": [30, 30, 0],
		"Rarity":  "Common",
	},
	"wasp": {
		"Cost":    5000,
		"Unit":    "wasp",
		"Count":   1,
		"OffsetX": [0],
		"OffsetY": [0],
		"Rarity":  "Common",
	},
}

var units = {
	"archengineer": {
		"mass":           0,
		"radius":         75,
		"type":           "Knight",
		"layer":          "Normal",
		"hp":             [2400],
		"sight":          350,
		"targettypes":    ["Troop"],
		"targetlayers":   ["Normal"],
		"attackdamage":   [50],
		"attackrange":    330,
		"attackinterval": 30,
		"preattackdelay": 10,
		"bulletlifetime": 10,
		"skill": {
			"wing": {
				"name":         "blastturret",
				"unit":         "blastturret",
				"castduration": 100,
				"precastdelay": 78,
			},
			"leader": {
				"arearatio":    120,
			},
		},
	},
	"archer": {
		"type":           "Troop",
		"layer":          "Normal",
		"mass":           6,
		"radius":         20,
		"hp":             [125],
		"sight":          350,
		"speed":          100,	#pixels per second
		"targettypes":    ["Troop", "Building", "Knight"],
		"targetlayers":   ["Normal"],
		"attackdamage":   [40, 60, 90],
		"attackrange":    250,
		"attackinterval": 12,
		"preattackdelay": 0,
		"bulletlifetime": 6,
	},
	"archsapper": {
		"mass":           0,
		"radius":         75,
		"type":           "Knight",
		"layer":          "Normal",
		"hp":             [2400],
		"sight":          350,
		"targettypes":    ["Troop"],
		"targetlayers":   ["Normal"],
		"attackdamage":   [50],
		"attackrange":    350,
		"attackinterval": 10,
		"preattackdelay": 0,
		"bulletlifetime": 10,
		"skill": {
			"wing": {
				"unit":         "cannon",
				"castduration": 100,
				"precastdelay": 82,
			},
			"leader": {
				"unit":         "cannon",
				"count":        2,
				"posX":         [325, 675],	 # pos based on blue side
				"posY":         [1075, 1075],
				"hpratio":      [300, 310, 320],
			},
		},
	},
	"astra": {
		"mass":           1000,
		"radius":         95,
		"type":           "Knight",
		"layer":          "Normal",
		"hp":             [2400],
		"sight":          350,
		"speed":          300,
		"targettypes":    ["Troop"],
		"targetlayers":   ["Normal"],
		"attackdamage":   [5],
		"attackrange":    350,
		"attackinterval": 1,
		"skill": {
			"wing": {
				"damage":   [10, 15, 20],
				"duration": 80,
				"start":    10,
				"end":      58,
				"width":    25,
				"height":   500,
			},
			"leader": {
				"hpratio":  [120, 130, 140],
			},
		},
	},
	"barrack": {
		"type":           "Building",
		"layer":          "Normal",
		"mass":           0,
		"radius":         60,
		"tilenumx":       3,
		"tilenumy":       3,
		"hp":             [1100],
		"spawn":          "footman",
		"spawninterval":  140,
		"spawncount":     2,
		"spawnoffsetX":   [-20, 20],
		"spawnoffsetY":   [0, 0],
		"decaydamage":    1,
	},
	"berserker": {
		"type":           "Troop",
		"layer":          "Normal",
		"mass":           6,
		"radius":         30,
		"hp":             [600],
		"sight":          350,
		"speed":          150,	#pixels per second
		"targettypes":    ["Troop", "Building", "Knight"],
		"targetlayers":   ["Normal"],
		"attackdamage":   [325, 70, 100],
		"attackrange":    40,
		"attackinterval": 20,
		"preattackdelay": 6,
	},
	"blaster": {
		"type":           "Troop",
		"layer":          "Normal",
		"mass":           10,
		"radius":         30,
		"hp":             [150],
		"sight":          400,
		"speed":          150,
		"targettypes":    ["Troop", "Building", "Knight"],
		"targetlayers":   ["Normal"],
		"attackdamage":   [100, 450, 600],
		"attackrange":    250,
		"attackinterval": 19,
		"preattackdelay": 0,
		"bulletlifetime": 19,
	},
	"blastturret": {
		"type":           "Building",
		"layer":          "Normal",
		"mass":           0,
		"radius":         40,
		"tilenumx":       3,
		"tilenumy":       3,
		"hp":             [640],
		"sight":          350,
		"targettypes":    ["Troop", "Building", "Knight"],
		"targetlayers":   ["Normal"],
		"attackdamage":   [100],
		"attackrange":    300,
		"attackinterval": 16,
		"preattackdelay": 0,
		"bulletlifetime": 15,
		"decaydamage":    1,
	},
	"cannon": {
		"type":           "Building",
		"layer":          "Normal",
		"mass":           0,
		"radius":         30,
		"tilenumx":       3,
		"tilenumy":       3,
		"hp":             [350],
		"sight":          350,
		"targettypes":    ["Troop", "Building", "Knight"],
		"targetlayers":   ["Normal"],
		"attackdamage":   [60],
		"attackrange":    275,
		"attackinterval": 8,
		"preattackdelay": 0,
		"bulletlifetime": 5,
		"decaydamage":    1,
	},
	"champion": {
		"type":           "Troop",
		"layer":          "Normal",
		"mass":           6,
		"radius":         30,
		"hp":             [775],		
		"shield":         [150],
		"sight":          350,
		"speed":          100,	#pixels per second
		"targettypes":    ["Troop", "Building", "Knight"],
		"targetlayers":   ["Normal"],
		"attackdamage":   [155, 70, 100],
		"attackrange":    40,
		"attackinterval": 13,
		"preattackdelay": 5,
		"chargedelay":           20,
		"chargedmovespeed":      300,
		"chargedattackdamage":   [310, 450, 550],
		"chargedattackinterval": 7,
		"chargedattackpredelay": 4,
	},
	"drillram": {
		"type":           "Troop",
		"layer":          "Normal",
		"mass":           10,
		"radius":         30,
		"hp":             [800],
		"sight":          350,
		"speed":          200,	#pixels per second
		"targettypes":    ["Building", "Knight"],
		"targetlayers":   ["Normal"],
		"attackdamage":   [210, 60, 90],
		"attackrange":    40,
		"attackinterval": 20,
		"preattackdelay": 9,
	},
	"enforcer": {
		"type":           "Troop",
		"layer":          "Normal",
		"mass":           6,
		"radius":         40,
		"hp":             [880],
		"sight":          350,
		"speed":          100,	#pixels per second
		"targettypes":    ["Troop", "Building", "Knight"],
		"targetlayers":   ["Normal"],
		"attackdamage":   [312, 70, 100],
		"attackrange":    40,
		"attackradius":   80,
		"attackinterval": 40,
		"preattackdelay": 10,
	},
	"felhound": {
		"type":           "Troop",
		"layer":          "Normal",
		"mass":           10,
		"radius":         15,
		"hp":             [32],
		"shield":         [50],
		"sight":          350,
		"speed":          200,
		"targettypes":    ["Troop", "Building", "Knight"],
		"targetlayers":   ["Normal"],
		"attackdamage":   [96, 60, 90],
		"attackrange":    30,
		"attackinterval": 30,
		"preattackdelay": 10,
	},
	"footman": {
		"type":           "Troop",
		"layer":          "Normal",
		"mass":           6,
		"radius":         25,
		"hp":             [300],
		"sight":          350,
		"speed":          100,	#pixels per second
		"targettypes":    ["Troop", "Building", "Knight"],
		"targetlayers":   ["Normal"],
		"attackdamage":   [75, 70, 100],
		"attackrange":    40,
		"attackinterval": 15,
		"preattackdelay": 5,
	},
	"frost": {
		"mass":           0,
		"radius":         70,
		"type":           "Knight",
		"layer":          "Normal",
		"hp":             [2400],
		"sight":          350,
		"targettypes":    ["Troop"],
		"targetlayers":   ["Normal"],
		"attackdamage":   [100],
		"attackrange":    350,
		"attackinterval": 20,
		"preattackdelay": 0,
		"bulletlifetime": 2,
		"skill": {
			"wing": {
				"radius":       100,
				"castduration": 70,
				"precastdelay": 20,
			},
			"leader": {
				"slowduration": [20],
			},
		},
	},
	"gargoyle": {
		"type":           "Troop",
		"layer":          "Normal",
		"mass":           6,
		"radius":         25,
		"hp":             [90],
		"shield":         [50],
		"sight":          350,
		"speed":          150,	#pixels per second
		"targettypes":    ["Troop", "Building", "Knight"],
		"targetlayers":   ["Normal"],
		"attackdamage":   [40, 60, 90],
		"attackrange":    100,
		"attackinterval": 10,
		"preattackdelay": 5,
	},
	"gargoyleking": {
		"type":           "Troop",
		"layer":          "Normal",
		"mass":           6,
		"radius":         35,
		"hp":             [395],
		"shield":         [100],
		"sight":          350,
		"speed":          100,	#pixels per second
		"targettypes":    ["Troop", "Building", "Knight"],
		"targetlayers":   ["Normal"],
		"attackdamage":   [147, 60, 90],
		"attackrange":    100,
		"attackinterval": 15,
		"preattackdelay": 5,
	},
	"giant": {
		"type":           "Troop",
		"layer":          "Normal",
		"mass":           60,
		"radius":         60,
		"hp":             [2000],
		"sight":          350,
		"speed":          75,	#pixels per second
		"targettypes":    ["Building", "Knight"],
		"targetlayers":   ["Normal"],
		"attackdamage":   [163, 60, 90],
		"attackrange":    40,
		"attackinterval": 20,
		"preattackdelay": 8,
	},
	"ironcoffin": {
		"mass":           1000,
		"radius":         110,
		"type":           "Knight",
		"layer":          "Normal",
		"hp":             [2400],
		"sight":          350,
		"speed":          300,
		"targettypes":    ["Troop"],
		"targetlayers":   ["Normal"],
		"attackdamage":   [75],
		"attackrange":    350,
		"attackinterval": 15,
		"preattackdelay": 0,
		"bulletlifetime": 15,
		"skill": {
			"wing": {
				"unit":         "sentryshelter",
				"castduration": 50,
				"precastdelay": 20,
			},
			"leader": {
				"unit":    "sentry",
				"perstep": 300,
			},
		},
	},
	"jouster": {
		"type":           "Troop",
		"layer":          "Normal",
		"mass":           6,
		"radius":         30,
		"hp":             [1215],
		"sight":          350,
		"speed":          100,	#pixels per second
		"targettypes":    ["Troop", "Building", "Knight"],
		"targetlayers":   ["Normal"],
		"attackdamage":   [245, 70, 100],
		"attackrange":    40,
		"attackinterval": 14,
		"preattackdelay": 5,
		"chargedelay":           20,
		"chargedmovespeed":      300,
		"chargedattackdamage":   [490, 450, 550],
		"chargedattackinterval": 6,
		"chargedattackpredelay": 3,
	},
	"judge": {
		"mass":           0,
		"radius":         85,
		"type":           "Knight",
		"layer":          "Normal",
		"hp":             [2400],
		"sight":          350,
		"targettypes":    ["Troop"],
		"targetlayers":   ["Normal"],
		"attackdamage":   [100],
		"attackrange":    375,
		"attackinterval": 20,
		"preattackdelay": 1,
		"bulletlifetime": 2,
		"skill": {
			"wing": {
				"damage":           [300, 400, 500],
				"radius":           70,
				"castduration":     100,
				"precastdelay":     78,
			},
			"leader": {
				"attackrangeratio": [120, 130, 140],
			},
		},
	},
	"lancer": {
		"mass":           1000,
		"radius":         105,
		"type":           "Knight",
		"layer":          "Normal",
		"hp":             [2400],
		"sight":          350,
		"speed":          300,
		"targettypes":    ["Troop"],
		"targetlayers":   ["Normal"],
		"attackdamage":   [50],
		"attackrange":    350,
		"attackinterval": 22,
		"preattackdelay": 0,
		"bulletlifetime": 22,
		"skill": {
			"wing": {
				"castduration":   40,
				"precastdelay":   25,
				"damageduration": 50,
				"damage":         30,
				"width":          100,
				"height":         100,
			},
			"leader": {
				"duration":       600,
				"damage":         30,
				"count":          2,
				"posX":           [225, 775], # pos based on blue side
				"posY":           [850, 850],
				"width":          75,
				"height":         50,
			},
		},
	},
	"legion": {
		"mass":           0,
		"radius":         70,
		"type":           "Knight",
		"layer":          "Normal",
		"hp":             [2400],
		"sight":          350,
		"targettypes":    ["Troop"],
		"targetlayers":   ["Normal"],
		"attackdamage":   [50],
		"attackrange":    350,
		"attackinterval": 2,
		"preattackdelay": 1,
		"bulletlifetime": 10,
		"skill": {
			"wing": {
				"damage":       [325, 400, 500],
				"radius":       70,
				"castduration": 40,
				"precastdelay": 20,
			},
			"leader": {
				"attackdamageratio": [110, 130, 140],
			},
		},
	},
	"nagmash": {
		"mass":           1000,
		"radius":         105,
		"type":           "Knight",
		"layer":          "Normal",
		"hp":             [2400],
		"sight":          350,
		"speed":          300,
		"targettypes":    ["Troop"],
		"targetlayers":   ["Normal"],
		"attackdamage":   [5],
		"attackrange":    350,
		"attackinterval": 1,
		"skill": {
			"wing": {
				"unit":         "footman",
				"count":        4,
				"offsetX":      [-30, 30, -30, 30],
				"offsetY":      [-30, -30, 30, 30],
				"castduration": 50,
				"precastdelay": 20,
			},
			"leader": {
				"unit":         "footman",
				"count":        4,
				"offsetX":      [-30, 30, -30, 30],
				"offsetY":      [-30, -30, 30, 30],
				"perstep":      300,
			},
		},
	},
	"ogre": {
		"type":           "Troop",
		"layer":          "Normal",
		"mass":           6,
		"radius":         35,
		"hp":             [2610],
		"sight":          350,
		"speed":          75,	#pixels per second
		"targettypes":    ["Troop", "Building", "Knight"],
		"targetlayers":   ["Normal"],
		"attackdamage":   [500, 70, 100],
		"attackrange":    40,
		"attackinterval": 20,
		"preattackdelay": 6,
	},
	"panzerkunstler": {
		"type":           "Troop",
		"layer":          "Normal",
		"mass":           6,
		"radius":         30,
		"hp":             [800],
		"sight":          350,
		"speed":          100,	#pixels per second
		"targettypes":    ["Troop", "Building", "Knight"],
		"targetlayers":   ["Normal"],
		"attackdamage":   [500, 70, 100],
		"attackrange":    40,
		"attackinterval": 30,
		"preattackdelay": 15,
		"powerattackdamage":    [100, 200, 300],
		"powerattackinterval":  50,
		"powerattackpredelay":  33,
		"powerattackfrequency": 3,
		"powerattackradius":    300,
		"powerattackforce":     3000,
	},
	"pixie": {
		"type":           "Troop",
		"layer":          "Ether",
		"mass":           6,
		"radius":         15,
		"hp":             [30],
		"sight":          350,
		"speed":          150,	#pixels per second
		"targettypes":    ["Troop", "Building", "Knight"],
		"targetlayers":   ["Normal"],
		"attackdamage":   [60, 70, 100],
		"attackrange":    40,
		"attackinterval": 20,
		"preattackdelay": 4,
	},
	"pixiegeode": {
		"type":          "Building",
		"layer":         "Normal",
		"mass":          0,
		"radius":        60,
		"tilenumx":      3,
		"tilenumy":      3,
		"hp":            [1100],
		"spawn":         "pixie",
		"spawninterval": 140,
		"spawncount":    1,
		"spawnoffsetX":  [0],
		"spawnoffsetY":  [0],
		"decaydamage":   1,
	},
	"pixieking": {
		"mass":           1000,
		"radius":         110,
		"type":           "Knight",
		"layer":          "Normal",
		"hp":             [2400],
		"sight":          350,
		"targettypes":    ["Troop"],
		"targetlayers":   ["Normal"],
		"attackdamage":   [50],
		"attackrange":    350,
		"attackinterval": 10,
		"preattackdelay": 1,
		"bulletlifetime": 8,
		"skill": {
			"wing": {
				"unit":         "pixiegeode",
				"castduration": 50,
				"precastdelay": 20,
			},
			"leader": {
				"unit":    "pixie",
				"perstep": 300,
				"count":   8,
				"offsetX": [-105, -75, -45, -15, 15, 45, 75, 105],
				"offsetY": [0, 0, 0, 0, 0, 0, 0, 0],
			},
		},
	},
	"psabu": {
		"type":           "Troop",
		"layer":          "Normal",
		"mass":           60,
		"radius":         40,
		"hp":             [2700],
		"shield":         [500],
		"sight":          350,
		"speed":          100,
		"targettypes":    ["Troop", "Building", "Knight"],
		"targetlayers":   ["Normal"],
		"attackdamage":   [800, 60, 90],
		"attackrange":    30,
		"attackinterval": 50,
		"attackradius":   80,
		"preattackdelay": 28,
		"absorbforce":    2000,
		"absorbdamage":   2,
		"absorbradius":   500,
	},
	"sentry": {
		"type":           "Troop",
		"layer":          "Normal",
		"mass":           6,
		"radius":         20,
		"hp":             [52],
		"sight":          350,
		"speed":          200,	#pixels per second
		"targettypes":    ["Troop", "Building", "Knight"],
		"targetlayers":   ["Normal"],
		"attackdamage":   [24, 60, 90],
		"attackrange":    250,
		"attackinterval": 13,
		"preattackdelay": 0,
		"bulletlifetime": 6,
	},
	"sentryshelter": {
		"type":          "Building",
		"layer":         "Normal",
		"mass":          0,
		"radius":        60,
		"tilenumx":      3,
		"tilenumy":      3,
		"hp":            [1100],
		"spawn":         "sentry",
		"spawninterval": 140,
		"spawncount":    1,
		"spawnoffsetX":  [0],
		"spawnoffsetY":  [0],
		"decaydamage":   1,
	},
	"shadowvision": {
		"type":           "Troop",
		"layer":          "Ether",
		"mass":           20,
		"radius":         35,
		"hp":             [800],
		"shield":         300,
		"sight":          400,
		"speed":          150,
		"targettypes":    ["Troop", "Building", "Knight"],
		"targetlayers":   ["Normal"],
		"attackdamage":   [300, 450, 600],
		"attackrange":    175,
		"attackinterval": 20,
		"preattackdelay": 0,
		"bulletlifetime": 20,
	},
	"starfire": {
		"type":           "Troop",
		"layer":          "Normal",
		"mass":           6,
		"radius":         30,
		"hp":             [340],
		"sight":          350,
		"speed":          100,	#pixels per second
		"targettypes":    ["Troop", "Building", "Knight"],
		"targetlayers":   ["Normal"],
		"attackdamage":   [100, 60, 90],
		"attackrange":    300,
		"attackinterval": 11,
		"preattackdelay": 0,
		"bulletlifetime": 6,
	},
	"tombstone": {
		"mass":           1000,
		"radius":         110,
		"type":           "Knight",
		"layer":          "Normal",
		"hp":             [2400],
		"sight":          350,
		"speed":          300,
		"targettypes":    ["Troop"],
		"targetlayers":   ["Normal"],
		"attackdamage":   [5],
		"attackrange":    350,
		"attackinterval": 1,
		"skill": {
			"wing": {
				"name":         "barrack",
				"unit":         "barrack",
				"castduration": 50,
				"precastdelay": 20,
			},
			"leader": {
				"name":         "lemming",
				"unit":         "footman",
				"count":        1,
				"offsetX":      150,
				"perdeaths":    4,
			},
		},
	},
	"trainee": {
		"type":           "Troop",
		"layer":          "Normal",
		"mass":           6,
		"radius":         20,
		"hp":             [50],
		"sight":          350,
		"speed":          200,	#pixels per second
		"targettypes":    ["Troop", "Building", "Knight"],
		"targetlayers":   ["Normal"],
		"attackdamage":   [48, 70, 100],
		"attackrange":    40,
		"attackinterval": 12,
		"preattackdelay": 5,
	},
	"wasp": {
		"type":           "Troop",
		"layer":          "Normal",
		"mass":           6,
		"radius":         25,
		"hp":             [1050],
		"shield":         [500],
		"sight":          300,
		"speed":          100,	#pixels per second
		"targettypes":    ["Building", "Knight"],
		"targetlayers":   ["Normal"],
		"attackdamage":   [600, 60, 90],
		"attackrange":    75,
		"attackinterval": 10,
		"preattackdelay": 7,
		"destroydamage":  [600],
		"destroyradius":  100,
	},
}